// auth.js
export const LOGOUT = 'LOGOUT';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

// lang.js
export const SET_LOCALE = 'SET_LOCALE';

// statistics.js
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';
export const FETCH_STATISTIC_FAILURE = 'FETCH_STATISTIC_FAILURE';

// customer-types.js
export const FETCH_CUSTOMER_TYPE_SUCCESS = 'FETCH_CUSTOMER_TYPE_SUCCESS';
export const FETCH_CUSTOMER_TYPE_FAILURE = 'FETCH_CUSTOMER_TYPE_FAILURE';
